-- -- Create a simple statusbar
-- local bar = CreateFrame("StatusBar", "MyStatusBar", UIParent)
-- bar:SetWidth(200)
-- bar:SetHeight(20)
-- bar:SetPoint("CENTER", 0, 0)
-- bar:SetStatusBarTexture("Interface\\TargetingFrame\\UI-StatusBar")
-- bar:SetStatusBarColor(0, 0.7, 0)
-- bar:SetMinMaxValues(0, 100)
-- bar:SetValue(50)

-- -- Add a background
-- local bg = bar:CreateTexture(nil, "BACKGROUND")
-- bg:SetAllPoints()
-- bg:SetTexture("Interface\\TargetingFrame\\UI-StatusBar")
-- bg:SetVertexColor(0.1, 0.1, 0.1, 0.8)

-- -- Update bar with player health
-- bar:RegisterEvent("UNIT_HEALTH")
-- bar:RegisterEvent("PLAYER_ENTERING_WORLD")
-- bar:SetScript("OnEvent", function()
--     local health = UnitHealth("player")
--     local maxHealth = UnitHealthMax("player")
--     this:SetMinMaxValues(0, maxHealth)
--     this:SetValue(health)

--     -- Color based on health percentage
--     local healthPercent = health / maxHealth
--     if healthPercent > 0.5 then
--         this:SetStatusBarColor(0, 0.7, 0)  -- Green when > 50%
--     elseif healthPercent > 0.2 then
--         this:SetStatusBarColor(1, 0.7, 0)  -- Yellow when 20-50%
--     else
--         this:SetStatusBarColor(1, 0, 0)    -- Red when < 20%
--     end
-- end)
